[package]
name = "focustree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
writable = { path = "../writable" }

[lib]
name = "focustree"
path = "focustree.rs"
