name: Continuous-Testing
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
      - working-directory: go/
        run: go mod tidy
      - run: go test ../test/counter ../test/danger ../test/novel ../test/nullValue ../test/zoo
