name: Continuous-Testing
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.1"
      - run: go mod tidy
      - run: go test ./test/counter ./test/novel ./test/zoo
