name: Continuous-Testing
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.6"
      - working-directory: test/counter
        run: go test
      - working-directory: test/danger
        run: go test
      - working-directory: test/novel
        run: go test
      - working-directory: test/nullValue
        run: go test
      - working-directory: test/zoo
        run: go test
